---
# Source: productcatalog/templates/persistentVolumeClaim-mongodb.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: r1-mongodb-pv-claim
  labels:
    oda.tmforum.org/componentName: r1-productcatalog
spec:
  storageClassName: default-st1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: productcatalog/templates/service-mongodb.yaml
apiVersion: v1
kind: Service
metadata:
  name: r1-mongodb
  labels:
    oda.tmforum.org/componentName: r1-productcatalog
    app: r1-mongodb
spec:
  ports:
  - port: 27017
    targetPort: r1-mongodb
    name: r1-mongodb
  type: NodePort
  selector:
    app: r1-mongodb
---
# Source: productcatalog/templates/service-partyroleapi.yaml
apiVersion: v1
kind: Service
metadata:
  name: r1-partyroleapi
  labels:
    app: r1-partyroleapi
    oda.tmforum.org/componentName: r1-productcatalog
spec:
  ports:
  - port: 8080
    targetPort: r1-prapi
    name: r1-partyroleapi
  type: NodePort
  selector:
    app: r1-partyroleapi
---
# Source: productcatalog/templates/service-productcatalogapi.yaml
apiVersion: v1
kind: Service
metadata:
  name: r1-prodcatapi
  labels:
    app: r1-prodcatapi
    oda.tmforum.org/componentName: r1-productcatalog
spec:
  ports:
  - port: 8080
    targetPort: r1-pcapi
    name: r1-prodcatapi
  type: NodePort
  selector:
    app: r1-prodcatapi
---
# Source: productcatalog/templates/deployment-mongodb.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1-mongodb
  labels:
    oda.tmforum.org/componentName: r1-productcatalog
    app: r1-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r1-mongodb
  template:
    metadata:
      labels:
        app: r1-mongodb
    spec:
      containers:
      - name: r1-mongodb
        image: mongo:latest
        ports:
        - name: r1-mongodb
          containerPort: 27017
        volumeMounts:
        - name: r1-mongodb-pv-storage
          mountPath: "/data/db"
      volumes:
      - name: r1-mongodb-pv-storage
        persistentVolumeClaim:
          claimName: r1-mongodb-pv-claim
---
# Source: productcatalog/templates/deployment-partyroleapi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1-partyroleapi
  labels:
    oda.tmforum.org/componentName: r1-productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r1-partyroleapi
  template:
    metadata:
      labels:
        app: r1-partyroleapi
    spec:
      containers:
      - name: r1-partyroleapi
        image: lesterthomas/partyroleapi:latest
        env:
        - name: RELEASE_NAME
          value: r1           
        - name: COMPONENT_NAME
          value: r1-productcatalog           
        imagePullPolicy: Always
        ports:
        - name: r1-prapi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /r1-productcatalog/tmf-api/partyRoleManagement/v4/partyRole 
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5          
          failureThreshold: 30
---
# Source: productcatalog/templates/deployment-productcatalogapi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1-prodcatapi
  labels:
    oda.tmforum.org/componentName: r1-productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r1-prodcatapi
  template:
    metadata:
      labels:
        app: r1-prodcatapi
    spec:
      containers:
      - name: r1-prodcatapi
        image: lesterthomas/productcatalogapi:latest
        env:
        - name: RELEASE_NAME
          value: r1           
        - name: COMPONENT_NAME
          value: r1-productcatalog           
        imagePullPolicy: Always
        ports:
        - name: r1-pcapi
          containerPort: 8080
---
# Source: productcatalog/templates/cronjob-roleinitialization.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: r1-roleinitialization
  labels:
    oda.tmforum.org/componentName: r1-productcatalog
spec:
  template:
    metadata:
      labels:
        app: r1-roleinitialization
    spec:
      containers:
      - name: r1-roleinitialization
        image: lesterthomas/roleinitialization:latest
        env:
        - name: RELEASE_NAME
          value: r1           
        - name: COMPONENT_NAME
          value: r1-productcatalog           
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 10
---
# Source: productcatalog/templates/component-productcatalog.yaml
apiVersion: oda.tmforum.org/v1alpha3
kind: component
metadata:
  name: r1-productcatalog
  labels:
    oda.tmforum.org/componentName: r1-productcatalog
spec:
  type: productcatalog
  selector:
    matchLabels:
     oda.tmforum.org/componentName: r1-productcatalog
  componentKinds:
  - group: core
    kind: Service    
  - group: core
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment  
  version: "0.0.1"
  description: "Simple Product Catalog ODA-Component from Open-API reference implementation." 
  maintainers:
  - name: Lester Thomas
    email: lester.thomas@vodafone.com
  owners:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com     
  coreFunction:
    exposedAPIs: 
    - name: productcatalogmanagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-productcatalog-v4.0.0.swagger.json
      implementation: r1-prodcatapi
      path: /r1-productcatalog/tmf-api/productCatalogManagement/v4
      developerUI: /r1-productcatalog/tmf-api/productCatalogManagement/v4/docs
      port: 8080
    dependentAPIs: 
    - name: party      
      specification: https://open-api.tmforum.org/TMF632-Party-v4.0.0.swagger.json  
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  management: []
  security:
    controllerRole: Admin
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
    partyrole:
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
      implementation: r1-partyroleapi
      path: /r1-productcatalog/tmf-api/partyRoleManagement/v4
      developerUI: /r1-productcatalog/tmf-api/partyRoleManagement/v4/docs
      port: 8080 
