---
# Source: productcatalog/templates/persistentVolumeClaim-mongodb.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: r1-mongodb-pv-claim
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: productcatalog/templates/service-mongodb.yaml
apiVersion: v1
kind: Service
metadata:
  name: r1-mongodb
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
    app: r1-productcatalogmanagement
spec:
  ports:
  - port: 27017
    targetPort: r1-mongodb
    name: tcp-r1-mongodb
  type: NodePort
  selector:
    impl: r1-mongodb
---
# Source: productcatalog/templates/service-partyroleapi.yaml
apiVersion: v1
kind: Service
metadata:
  name: r1-partyroleapi
  labels:
    app: r1-productcatalogmanagement
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  ports:
  - port: 8080
    targetPort: r1-prapi
    name: http-r1-partyroleapi
  type: NodePort
  selector:
    impl: r1-partyroleapi
---
# Source: productcatalog/templates/service-productcatalogapi.yaml
apiVersion: v1
kind: Service
metadata:
  name: r1-prodcatapi
  labels:
    app: r1-productcatalogmanagement
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  ports:
  - port: 8080
    targetPort: r1-pcapi
    name: http-r1-prodcatapi
  type: NodePort
  selector:
    impl: r1-prodcatapi
---
# Source: productcatalog/templates/service-registerallevents.yaml
apiVersion: v1
kind: Service
metadata:
  name: r1-productcatalogmanagement-sm
  labels:
    name: r1-productcatalogmanagement-sm
    app: r1-productcatalogmanagement
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  ports:
  - port: 4000
    name: http-r1-productcatalogmanagement-sm
  type: NodePort
  selector:
    impl: r1-metricsapi
---
# Source: productcatalog/templates/deployment-metricsapi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1-metricsapi
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: r1-metricsapi
  template:
    metadata:
      labels:
        app: r1-productcatalogmanagement
        impl: r1-metricsapi
        version: lesterthomas-metricsapi-latest
    spec:
      containers:
      - name: r1-registerallevents
        image: lesterthomas/registerallevents:latest
        env:
        - name: RELEASE_NAME
          value: r1           
        - name: COMPONENT_NAME
          value: r1-productcatalogmanagement           
        imagePullPolicy: Always
        ports:
        - name: r1-prapi
          containerPort: 4000
---
# Source: productcatalog/templates/deployment-mongodb.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1-mongodb
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: r1-mongodb
  template:
    metadata:
      labels:
        impl: r1-mongodb
        app: r1-productcatalogmanagement
        version: mongo-latest
    spec:
      containers:
      - name: r1-mongodb
        image: mongo:5.0.1
        ports:
        - name: r1-mongodb
          containerPort: 27017
        volumeMounts:
        - name: r1-mongodb-pv-storage
          mountPath: "/data/db"
      volumes:
      - name: r1-mongodb-pv-storage
        persistentVolumeClaim:
          claimName: r1-mongodb-pv-claim
---
# Source: productcatalog/templates/deployment-partyroleapi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1-partyroleapi
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: r1-partyroleapi
  template:
    metadata:
      labels:
        app: r1-productcatalogmanagement
        impl: r1-partyroleapi
        version: lesterthomas-partyroleapi-latest
    spec:
      containers:
      - name: r1-partyroleapi
        image: csotiriou/partyroleapi:0.4
        env:
        - name: RELEASE_NAME
          value: r1
        - name: COMPONENT_NAME
          value: r1-productcatalogmanagement
        - name: MONGODB_HOST
          value: r1-mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: tmf
        - name: NODE_ENV
          value: production
        imagePullPolicy: Always
        ports:
        - name: r1-prapi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /r1-productcatalogmanagement/tmf-api/partyRoleManagement/v4/partyRole
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
---
# Source: productcatalog/templates/deployment-productcatalogapi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1-prodcatapi
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: r1-prodcatapi
  template:
    metadata:
      labels:
        app: r1-productcatalogmanagement
        impl: r1-prodcatapi
        version: csotiriou-productcatalogapi-0-10
    spec:
      containers:
      - name: r1-prodcatapi
        image: csotiriou/productcatalogapi:0.10
        env:
        - name: RELEASE_NAME
          value: r1
        - name: COMPONENT_NAME
          value: r1-productcatalogmanagement
        - name: OTL_EXPORTER_CONSOLE_ENABLED
          value: "false"
        - name: OTL_EXPORTER_TRACE_PROTO_ENABLED
          value: "true"
        - name: OTL_EXPORTER_TRACE_PROTO_COLLECTOR_URL
          value: http://datadog-agent.default.svc.cluster.local:4318/v1/traces
        - name: MONGODB_HOST
          value: r1-mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: tmf
        - name: NODE_ENV
          value: production
        imagePullPolicy: Always
        ports:
        - name: r1-pcapi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /r1-productcatalogmanagement/tmf-api/productCatalogManagement/v4/catalog
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
---
# Source: productcatalog/templates/cronjob-productcataloginitialization.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: r1-productcataloginitialization
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  template:
    metadata:
      labels:
        app: r1-productcataloginitialization
    spec:
      containers:
      - name: r1-productcataloginitialization
        image: lesterthomas/productcataloginitialization:0.3
        env:
        - name: RELEASE_NAME
          value: r1           
        - name: COMPONENT_NAME
          value: r1-productcatalogmanagement           
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 10
---
# Source: productcatalog/templates/cronjob-roleinitialization.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: r1-roleinitialization
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  template:
    metadata:
      labels:
        app: r1-roleinitialization
    spec:
      containers:
      - name: r1-roleinitialization
        image: lesterthomas/roleinitialization:0.3
        env:
        - name: RELEASE_NAME
          value: r1           
        - name: COMPONENT_NAME
          value: r1-productcatalogmanagement           
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 10
---
# Source: productcatalog/templates/component-productcatalog.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: r1-productcatalogmanagement
  labels:
    oda.tmforum.org/componentName: r1-productcatalogmanagement
spec:
  id: TMFC001
  name: productcatalogmanagement
  functionalBlock: CoreCommerce
  publicationDate: 2023-08-18T00:00:00.000Z
  status: specified
  version: 0.0.1
  description: "Simple Product Catalog ODA-Component from Open-API reference implementation."

  maintainers:
  - name: Lester Thomas
    email: lester.thomas@vodafone.com
  owners:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com     
  coreFunction:
    exposedAPIs: 
    - name: productcatalogmanagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
      implementation: r1-prodcatapi
      apitype: openapi
      path: /r1-productcatalogmanagement/tmf-api/productCatalogManagement/v4
      developerUI: /r1-productcatalogmanagement/tmf-api/productCatalogManagement/v4/docs
      port: 8080
    dependentAPIs: 
    - name: party 
      apitype: openapi     
      specification: https://open-api.tmforum.org/TMF632-Party-v4.0.0.swagger.json  
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  managementFunction: 
    exposedAPIs: 
    - name: metrics
      apitype: prometheus
      implementation: r1-productcatalogmanagement-sm
      path: /r1-productcatalogmanagement/metrics
      port: 4000   
    dependentAPIs: [] 
  securityFunction:
    controllerRole: Admin
    exposedAPIs: 
    - name: partyrole
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
      implementation: r1-partyroleapi
      apitype: openapi
      path: /r1-productcatalogmanagement/tmf-api/partyRoleManagement/v4
      developerUI: /r1-productcatalogmanagement/tmf-api/partyRoleManagement/v4/docs
      port: 8080
    dependentAPIs: []
